# Generated by Django 2.0.7 on 2018-07-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20180718_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.IntegerField(max_length=20)),
                ('landlord', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
                ('hometown', models.CharField(max_length=30)),
            ],
        ),
    ]
