# Generated by Django 2.0.7 on 2018-07-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_home_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.IntegerField(),
        ),
    ]
