# Generated by Django 2.0.7 on 2018-07-22 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_auto_20180720_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=10000)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Home')),
            ],
        ),
    ]
